version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_TOKEN=7739649280:AAH_aXFnIlVKXRUlczzkZ1uc0iOZIJmNfc4
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=drillflow
      - DB_USER=postgres
      - DB_PASSWORD=drillflow_secure_password_2024
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=drillflow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=drillflow_secure_password_2024
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data: